# Generated by Django 4.2.4 on 2023-08-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head',
            field=models.CharField(max_length=255, unique=True, verbose_name='Заголовок'),
        ),
    ]
